package com.example.engine

import android.util.Base64

object WaterGrid {
    const val COLS = 168
    const val ROWS = 92
    const val CELL_SIZE = 100f
    const val WATER_SPEED_MULTIPLIER = 0.4f

    private const val WATER_B64 =
        "//////8DAAAAAAAAAAAAAAAAAAAA//////8DAAAAAAAAAAAAAAAAAAAA//////8DAAAAAAAAAAAAAAAAAAAA" +
        "//////8HAAAAAAAAAAAAAAAAAAAA//////8HAAAAAAAAAAAAAAAAAAAA//////8fAAAAAAAAAAAAAAAAAAAA" +
        "//////8fAAAAAAAAAAAAAAAAAAAA//////8PAAAAAAAAAAAAAAAAAAAA//////8fAAAAAAAAAAAAAAAAAAAA" +
        "//////9//gAAAAAAAAAAAAAAAAAA///////v8wAAAAAAAAAAAAAAAAAA//////9DgAAAAAAAAAAAAAAAAAAA" +
        "//////8DAAAAAAAAAAAAAAAAAAAA//////8DAAAAAAAAAAAAAAAAAAAA////f/8DAAAAAAAAAAAAAAAAAAAA" +
        "//+/A4cBAAAAAAAAAAAAAAAAAAAA//8PAAQAAAAAAAAAAAAAAAAAAAAA//8BAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/38AAAAAAAAAAAAAAAAAAAAAAAAA/x8AAAAAAAAAAAAAAAAAAAAAAAAA/w8AAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/w8AAAAAAAAAAAAAAAAAAAAAAAAAnw8AAAAAAAAAAAAAAAAAAAAAAAAA/wcAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/wcAAAAAAAAAAAAAAAAAAAAAAAAA/w0AAAAAAAAAAAAAAAAAAAAAAAAA/wcMAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/+cHAAAAAAAAAAAAAAAAAAAAAAAA/+cGAAAAAAAAAAAAAAAAAAAAAAAA/+d+AAAAAAAAAAAAAAAAAAAAAAAA" +
        "/28AAAAAAAAAAAAAAAAAAAAAAAAA/88AAAAAAAAAAAAAAAAAAAAAAAAA/98EAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/98+AAAAAAAAAAAAAAAAAAAAAAAA//8/AAAAAAAAAAAAAAAAAAAAAAAA//8/AAAAAAAAAAAAAAAAAAAAAAAA" +
        "//8gAAAAAAAAAAAAAAAAAAAAAAAA/w8AAAAAAAAAAAAAAAAAAAAAAAAA/wUAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/x8AAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAA//8BAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/38DAAAAAAAAAAAAAAAAAAAAAAAA//8HAAAAAAAAAAAAAAAAAAAAAAAA/48HAAAAAAAAAAAAAAAAAAAAAAAA" +
        "/78HEwAAAAAAAAAAAAAAAAAAAAAA/z8HNwAAAAAAAAAAAAAAAAAAAAAA/3+CPQAAAAAAAAAAAAAAAAAAAAAA" +
        "/3/8fwAAAAAAAAAAAAAAAAAAAAAA///8/w8AAAAAAAAAAAAAAAAAAAAA/////z8AAAAAAAAAAAAAAAAAAAAA" +
        "/////38AAAAAAAAAAAAAAAAAAAAA//////8BAAAAAAAAAAAAAAAAAAAA//////8PAAAAAAAAAAAAAAAAAAAA" +
        "/////z8fAAAAAAAAAAAAAAAAAAAA//////8/gAAAAAAAAAAAAAAAAAAA//////8/8AEAAAAAAAAAAAAAAAAA" +
        "//////+/zwAAAAAAAAAAAAAAAAAA//+P//+/HwAAAAAAAAAAAAAAAAAA///w//+/P34AAAAAAAAAAAAAAAAA" +
        "////////4D4AAAAAAAAAAAAAAAAA//////9/gj0AAAAAAAAAAAAAAAAA//////8ngw8AAAAAAAAAAAAAAAAA" +
        "//////9Hvw8AAAAAAAAAAAAAAAAA//////+H7w8AAAAAAAAAAAAAAAAA//////8P/w8AAAAAAAAAAAAAAAAA" +
        "/////////wsAAAAAAAAAAAAAAAAA//////////cMAAAAAAAAAAAAAAAA//////////8PAAAAAAAAAAAAAAAA" +
        "//////////EPAAAAAAAAAAAAAAAA/////////4MHAAAAAAAAAAAAAAAA/////////4cHAAAAAAAAAAAAAAAA" +
        "/////////49/AAAAAAAAAAAAAAAA/////////8//AAAAAAAAAAAAAAAA/////////995AAAAAAAAAAAAAAAA" +
        "/////////995AAAAAAAAAAAAAAAA//////////8xAAAAAAAAAAAAAAAA//////////8fAAAAAAAAAAAAAAAA" +
        "//////////8PAAAAAAAAAAAAAAAA//////////8PAAAAAAAAAAAAAAAA//////////8PAAAAAAAAAAAAAAAA" +
        "//////////8fAAAAAAAAAAAAAAAA//////////8/AAAAAAAAAAAAAAAA/////////x9/AAAAAAAAAAAAAAAA" +
        "/////////19+AAAAAAAAAAAAAAAA///////////PAAAAAAAAAAAAAAAA////////////AQAAAAAAAAAAAAAA" +
        "////////////AQAAAAAAAAAAAAAA//////////+fAQAAAAAAAAAAAAAA////////////AwAAAAAAAAAAAAAA" +
        "////////////AQAAAAAAAAAAAAAA////////////AQAAAAAAAAAAAAAA"

    private val gridBytes: ByteArray by lazy {
        try {
            Base64.decode(WATER_B64, Base64.DEFAULT)
        } catch (_: Exception) {
            ByteArray(0)
        }
    }

    fun isWater(x: Float, y: Float): Boolean {
        if (gridBytes.isEmpty()) return false
        val gx = (x / CELL_SIZE).toInt()
        val gy = (y / CELL_SIZE).toInt()
        if (gx < 0 || gy < 0 || gx >= COLS || gy >= ROWS) return false
        val bitIdx = gy * COLS + gx
        val byteIdx = bitIdx shr 3
        if (byteIdx >= gridBytes.size) return false
        val byteVal = gridBytes[byteIdx].toInt() and 0xFF
        val bit = (byteVal shr (bitIdx and 7)) and 1
        return bit == 1
    }
}
